language: node_js
os: linux
node_js:
  - "10"
jobs:
  include:
    - stage: testing
      if: branch in (master, develop)
      script: # if this is not set, it will run npm run test 
        - npm run test
    - stage: npm release
      # only release on master branch
      if: branch = master
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: true